name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to HostGator
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: ${{ secrets.PATH }}
          script: |
            cd ${{ secrets.PATH }}
            ./deploy.sh
