name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  web-deploy:
    name: 🎉 Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Step 2: Deploy files to the FTP server
      - name: 📂 Sync files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: . # Specify the directory to upload (default is the root of your repository)
          server-dir: ${{ secrets.FTP_PATH }} # Remote directory on your FTP server

      # Step 3 (Optional): Post-deployment script
      # If you need to execute commands on the server after uploading files
      - name: Run Post-deployment Script (Optional)
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            ./deploy.sh
