name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to Server
        run: |
          scp -r ./* ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:${{ secrets.PATH }}

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            ./deploy.sh
