name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: ${{ secrets.PATH }}
          script: "cd ${{ secrets.PATH }} && ./deploy.sh"